alias: Chargepoint Current Regulation
description: ""
trigger:
  - platform: time_pattern
    seconds: /4
    enabled: true
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: input_select.charge_mode
            state: Max Speed
        sequence:
          - service: input_number.set_value
            data:
              value: >-
                {% set newcurrent = states('input_number.main_maximal_current') | float(1) - states('sensor.shell3em_main_current') | float(2) * states('sensor.shell3em_main_power_factor') | float(3) + states('sensor.shelly3em_laadpaal_current') | float(2) %}
                {% if newcurrent < states('input_number.chargepoint_minimal_current') | float(1) -%}
                {{ states('input_number.chargepoint_minimal_current') | float(1) }}
                {% elif newcurrent > states('input_number.chargepoint_maximal_current') | float(1) -%}
                {{ states('input_number.chargepoint_maximal_current') | float(1) }}
                {%- else -%}
                {{ newcurrent }}
                {%- endif %}
            target:
              entity_id: input_number.chargepoint_desired_current
      - conditions:
          - condition: state
            entity_id: input_select.charge_mode
            state: Avoid Power To Grid
        sequence:
          - service: input_number.set_value
            data:
              value: >-
                {% set newcurrent = states('sensor.shelly3em_laadpaal_current') | float(1) - states('sensor.shell3em_main_current') | float(2) * states('sensor.shell3em_main_power_factor') | float(3) + 0.2 %}
                {% if newcurrent < states('input_number.chargepoint_minimal_current') | float(1) -%}
                {{ states('input_number.chargepoint_minimal_current') | float(1) }}
                {% elif newcurrent > states('input_number.chargepoint_maximal_current') | float(1) -%}
                {{ states('input_number.chargepoint_maximal_current') | float(1) }}
                {%- else -%}
                {{ newcurrent }}
                {%- endif %}
            target:
              entity_id: input_number.chargepoint_desired_current
      - conditions:
          - condition: state
            entity_id: input_select.charge_mode
            state: 2A From Grid
        sequence:
          - service: input_number.set_value
            data:
              value: >-
                {% set newcurrent = states('sensor.shelly3em_laadpaal_current') | float(1) - states('sensor.shell3em_main_current') | float(2) * states('sensor.shell3em_main_power_factor') | float(3) + 2 %}
                {% if newcurrent < states('input_number.chargepoint_minimal_current') | float(1) -%}
                {{ states('input_number.chargepoint_minimal_current') | float(1) }}
                {% elif newcurrent > states('input_number.chargepoint_maximal_current') | float(1) -%}
                {{ states('input_number.chargepoint_maximal_current') | float(1) }}
                {%- else -%}
                {{ newcurrent }}
                {%- endif %}
            target:
              entity_id: input_number.chargepoint_desired_current
      - conditions:
          - condition: state
            entity_id: input_select.charge_mode
            state: Solar only
        sequence:
          - service: input_number.set_value
            data:
              value: >-
                {% set newcurrent = states('sensor.sma_grid_phase_1_current') | float(1) %}
                {% if newcurrent < states('input_number.chargepoint_minimal_current') | float(1) -%}
                {{ states('input_number.chargepoint_minimal_current') | float(1) }}
                {% elif newcurrent > states('input_number.chargepoint_maximal_current') | float(1) -%}
                {{ states('input_number.chargepoint_maximal_current') | float(1) }}
                {%- else -%}
                {{ newcurrent }}
                {%- endif %}
            target:
              entity_id: input_number.chargepoint_desired_current
      - conditions:
          - condition: state
            entity_id: input_select.charge_mode
            state: Manual
        sequence:
          - service: input_number.set_value
            data:
              value: >-
                {% set newcurrent = states('input_number.chargepoint_manual_current') | float(1) %}
                {% if newcurrent < states('input_number.chargepoint_minimal_current') | float(1) -%}
                {{ states('input_number.chargepoint_minimal_current') | float(1) }}
                {% elif newcurrent > states('input_number.chargepoint_maximal_current') | float(1) -%}
                {{ states('input_number.chargepoint_maximal_current') | float(1) }}
                {%- else -%}
                {{ newcurrent }}
                {%- endif %}
            target:
              entity_id: input_number.chargepoint_desired_current
      - conditions:
          - condition: state
            entity_id: input_select.charge_mode
            state: Charging Off
        sequence:
          - service: input_number.set_value
            data:
              value: 0
            target:
              entity_id: input_number.chargepoint_desired_current
    enabled: true
  - choose:
      - conditions:
          - condition: template
            value_template: >-   ## desired - current + main > max
              {{states('input_number.chargepoint_desired_current') |float(1) - states('sensor.shelly3em_laadpaal_current') |float(1) + (states('sensor.shell3em_main_current') |float(2)) * states('sensor.shell3em_main_power_factor') | float(3) > states('input_number.main_maximal_current') |float(1) }}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {{ states('input_number.main_maximal_current') |float(1) - states('sensor.shell3em_main_current') |float(2) * states('sensor.shell3em_main_power_factor') | float(3) + states('sensor.shelly3em_laadpaal_current') |float(1) }}
            target:
              entity_id: input_number.chargepoint_desired_current
          - service: logbook.log
            data:
              name: chargepoint
              message: MAXING OUT on desired Current
              entity_id: input_number.main_maximal_current
    enabled: true
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) > 0.25 }}
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) <= 0.75}}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) - 0.1 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%}  
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) > 0.75 }}
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) <= 2.5 }}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) - 0.5 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%} 
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) > 2.5}}
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) <= 7.5}}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) - 1 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%}
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) > 7.5}}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) - 2 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%}
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) < - 0.25}}
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) >= -0.75}}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) + 0.1 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%}
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) < -0.75}}
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) >= -2.5}}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) + 0.5 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%}
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) < -2.5}}
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) >= -7.5}}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) + 1 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%}
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
      - conditions:
          - condition: template
            value_template: >-
              {{states('input_number.chargepoint_desired_current') |float(1) - (states('sensor.shelly3em_laadpaal_current') |float(1)) < -7.5}}
        sequence:
          - service: number.set_value
            data:
              value: >-
                {% set newvalue = states('number.modbus_server_xemex_ct3current') | float(1) + 2 %}
                {% if newvalue  >= 1 and newvalue <= 40 -%}
                {{ newvalue }}
                {%- else -%}
                {{ states('number.modbus_server_xemex_ct3current') | float(1) }}
                {%- endif %}
            target:
              entity_id: number.modbus_server_xemex_ct3current
    default:
      - service: number.set_value
        data:
          value: "{{ states('number.modbus_server_xemex_ct3current') | float(1) - 0 }}"
        target:
          entity_id: number.modbus_server_xemex_ct3current
    enabled: true
mode: single